apiVersion: batch/v1
kind: Job
metadata:
  name: node-app-job
spec:
  
  template:
   
    spec:
      containers:
      - name: node-app-job 
        image: alpine 
        command: ["sleep","40"]
        ##if the node get restarted or update your k8s cluster 
      restartPolicy: Never
  activeDeadlineSeconds: 15

