apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql 
  labels:
    app: mysql 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql 
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      containers:
      - name: mysql 
        image: mysql:5.6
        env: 
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db-password
                key: password
        ##3this is the volume mount point inside my container
        volumeMounts:
          - name: storage 
            mountPath: /var/lib/mysql
            ###config map can store 1MB of data it is like a volume
            #this is the path inside your container
          - name: configuration
            mountPath: /docker-entrypoint-initdb.d
        ports:
        - containerPort: 3306
      volume:
        - name: storage 
          persistentVolumeClaim:
            claimName: task-pv-claim
        - name: configuration
          configmap:
            name: userdb-creation-script
