apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-state
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce #readwritemany #read
  hostPath:
    path: "/mnt/data"