apiVersion: apps/v1
kind: Deployment 
metadata:
  name: usermgmt-webapp 
  labels:
    app: usermgmt-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-webapp
  template:
    metadata:
      labels:
        app: usermgmt-webapp
    spec:
    #i want to deploy my front end pod
    #before i deploy my frontend i want to ensure the connectivity to my database them only it should deploy my frontend. 
      
      containers:
        - name: usermgmt-webapp
          image: stacksimplify/kube-usermgmt-webapp
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOSTNAME
              value: "mysql"     
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME 
              value: "webappdb"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: password